### ISSUE TITLE
RGB Hat PCB V1?

### ISSUE THREAD

**Issue by twh73** [xfrings/RGB-MatrixDriver#1]
I think I ordered a set of PCBs from Oshpark just days before you uploaded V2. I am trying to figure out if these V1 boards are usable at all. From checking the pin-out of the displays and the raspberry PI it seems like the hat boards effectively have to be mounted "upside down" and the problem is that both the matrix and the raspberry PI would have to "plug in" on the same side of the board, right? I think it might be possible with a low profile IDC connector to make it work. Did you use the V1 board? do you maybe have a picture of how you installed the headers and how you used it?

**Comment by asterix** [comment]
Yes. I've used a set of V1s myself. But I did not use IDC connectors on them because I made the mistake of placing a chirally mirrored header on them. I used one set by soldering 8x2 headers and using a custom connector as I've shown in README. However, this got annoying  because I didn't want to use a custom connector with the hat! I think I know one solution: use a 90 degree IDC header mounted on the same side as the Raspberry Pi header. I've not done this myself though. You could also possibly solder regular 90 degree headers and use them with IDC connectors if you're careful with connection directions. I'll try to post images of soldered headers although V1 is hard as I've handed them to someone else.

**Comment by asterix** [comment]
I added some photos of revision 2 hat. But I guess this is not what you wanted. I'd really recommend ordering revision 2 PCBs (if this is a possibility) as they work great with IDC connectors.

I'll leave the issue open so that others who might have ordered revision 1 know this.

**Comment by acemodou** [comment]
Is it available to order .

**Comment by asterix** [comment]
Closing since V2 has been around long enough.
