### ISSUE TITLE
Compilation and GCC version

### ISSUE THREAD

**Issue by AST-esp-rasp** [xfrings/RGB-MatrixDriver#2]
compiling it with sudo make command I get the error that this -std=c++11 is an unknown command line option?

**Comment by asterix** [comment]
Can you check your GCC version (by typing gcc -v)?
-std=c++11 is only available on GCC versions >= 4.3. 

If your GCC is older you need to change the Makefile to use option -std=c++0x instead of -std=c++11. If it is even older, then C++11 might not be supported at all and you cannot compile this project without C++11 since a lot of this project relies on it.

However, my suggestion is to really update your GCC!

**Comment by asterix** [comment]
Closing assuming my previous comment fixed the issue.

**Comment by AST-esp-rasp** [comment]
gcc version is shown as 4.6.3
and exactly the error is " cclplus: error: unrecognized  command line option -std=c++11"

**Comment by asterix** [comment]
Which operating system are you using? Which version?
Can you try changing the "-std=c++11" to "-std=c++0x" in Makefile?

**Comment by AST-esp-rasp** [comment]
Raspbian GNU Linux 7 (wheezy)

**Comment by asterix** [comment]
Ok. You most definitely have to update your compiler to >=4.8 if you want to get this working correctly.
Check [this](https://community.thinger.io/t/starting-with-the-raspberry-pi/36), or [this](http://raspberrypi.stackexchange.com/questions/12325/how-can-i-install-gcc-4-8-on-the-raspberry-pi) post to update GCC.
