### ISSUE TITLE
pix-driver running on CORE3 is not backward compatible with Raspberry Pi 1

### ISSUE THREAD

**Issue by AST-esp-rasp** [xfrings/RGB-MatrixDriver#3]
After new Jessie install on my raspi I finally could compile
The HZELLER stuff is running fine to prevent rewiring i changed your code see comment below.
unfortunately the program seems to wait for something?
![image](https://cloud.githubusercontent.com/assets/20192717/16653292/4dc154f2-4450-11e6-8f99-e2ccaff8fdc9.png)
I have run it in debugger and it seems that the clock start it is waiting for in the gpio.cpp causes the problem i have.
As I told I changed the gpio port settings to prevent rewire the whole thing here are my setting
![image](https://cloud.githubusercontent.com/assets/20192717/16653471/32844d9c-4451-11e6-81ba-041461372708.png)
additionally i have a 32x64 display therefore i change this here:
![image](https://cloud.githubusercontent.com/assets/20192717/16653528/6f66adf4-4451-11e6-9fd9-542e4167344b.png)
Maybe you have any hints for me?

**Comment by asterix** [comment]
After configuring the PWM module, the busy flag is checked to make sure that the configuration is successful before exiting.

```
In rasp_pi_gpio.cpp
   // Wait until ON
   while((*(clkm_ + CM_PWMCTL_OFF) & CM_CTL_BUSY) == 0)
   {
      asm("");
   }
```

This should work as I've tried this on multiple Raspberry Pi 2s.

To debug, go to `logging.h` and enable logging by uncommenting DEBUG macro definition. Also, could you restart your board before trying again?

If it still doesn't work, try commenting those lines in `rasp_pi_gpio.cpp` to see if everything still works as expected.

Next, about the configuration for 64x32 matrix, what you've done is ok, but since these are really internal chains I would suggest:

```
#define MATRIX_LEN   32
#define MATRIX_HGT  32
#define NUM_CHAINED  2
```

Let me know how this goes.

**Comment by AST-esp-rasp** [comment]
![image](https://cloud.githubusercontent.com/assets/20192717/16688978/f2158a02-4520-11e6-8efc-42d191d08eeb.png)
Hello I enabled the debugger and commented out the while loop.
on the picture you can see what the debugger delivers.
Just to mention it I'm running it on a raspberry Pi 1 Model B+

**Comment by asterix** [comment]
```
:) :)
```

Thanks for mentioning that you're using Rasp Pi 1. Now the failures make sense because you're using a completely wrong peripheral address setting.

You need to change mapping to Rasp Pi 1.

```
In rasp_pi_gpio.h comment the RASP_PI_2 flag. To compile for Pi 1.

// Set the correct peripheral addresses
// Ref: BCM2835 ARM Peripherals
//#define RASP_PI_2        1

#ifdef RASP_PI_2
#define RASP_PI_X_BASE   0x3F000000
#else
#define RASP_PI_X_BASE   0x20000000
#endif
```

Next, I had `pix_driver` run on `CORE3` by default which wasn't backward compatible with Raspberry Pi 1. I've fixed this to move it to `CORE0` and it shouldn't throw that error anymore.
Pull the new version to tryout. (You still have to modify the above flag, since Raspberry Pi 2 is used by default)

**Comment by asterix** [comment]
Fixed in commit `db16999`

**Comment by AST-esp-rasp** [comment]
Hi
Now i have it running thanks a lot

**Comment by asterix** [comment]
Happy to hear! You shouldn't have to comment the checking on BUSY flag during PWM configuration now. It should work as expected.
